### ISSUE TITLE
simple-viewer-app tries to load missing files

### ISSUE THREAD

**Issue by aderderian** [imodeljs/imodeljs-samples#15]
For some reason after a clean pull, build, run, the simple viewer app is trying to load some files that do not exist in the output directory.

![image](https://user-images.githubusercontent.com/868165/74999599-0c4db400-542a-11ea-9cdd-7f4384458ee4.png)

**Comment by calebmshafer** [comment]
@aderderian by default iModel.js apps always try to load the pseudo localized locale when running in development, which is why it's making the request to load them.  However, it doesn't look like the app is setup to generate them from the English strings so it's failing to load them.

I'll take a look and update simple viewer app.  Thanks!

**Comment by aderderian** [comment]
Cool, thanks @calebmshafer

**Comment by calebmshafer** [comment]
Just pushed the update to the Simple Viewer App to run the pseudo-localization before the build, [commit](https://github.com/imodeljs/imodeljs-samples/commit/bf067e5290b1842a40adc5146a814ea2c9d630b1).
