### ISSUE TITLE
Invalid iModelToken for PRC operation request

### ISSUE THREAD

**Issue by bhec362587** [imodeljs/imodeljs-samples#6]
Hi,
when I try to open the offline iModel, there will be an error message:

![image](https://user-images.githubusercontent.com/49505211/57741991-c7099280-76f1-11e9-8250-82d24fc9d679.png)

"imjs_offline_imodel" has been defined in config. json.
"imjs_offline_imodel" : "assets/sample_documents/04_Plant.i.ibim"
How can I solve this?

Regards,

He

**Comment by wilmaier** [comment]
Hi Boris,

I discovered that due to recent changes, the feature of opening a snapshot imodel using the “Work Offline” button is no longer working.
A new version with a fix should be available in the next couple days.

One thing I should mention is that this feature is not supported for web apps.  
The ‘Work Offline’ button will only be available when the app is run as an electron app (npm run electron).

**Comment by wilmaier** [comment]
This issue is now resolved in the latest version.
